version: '3.4'

services:
  meetsport:
    image: ${DOCKER_REGISTRY-}meetsport
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - mariadb_default

networks:
  mariadb_default:
    external: true
